### PR TITLE
Make confirmation deadline editable fixes #187

### LINKED ISSUE #187: {{confirmation_deadline}} shows the wrong date
I'm not sure if I've understood this wrong or given in the wrong dates, so please help me out here.

I told the app the following details:
Screen Shot 2019-06-03 at 12 21 37 PM

So I'm going to choose the attendees and everything by 3rd of June midnight. I want the applicants to confirm their attendance by 5th of June midnight (so I'm giving them 2 full days to respond). 

But if I use the {{ confirmation_deadline }} tag, it should say 05.06.2019, but it says 08.06.2019 which is the workshop date. This is I think a bug. 🐛 

Screen Shot 2019-06-03 at 12 15 12 PM
Screen Shot 2019-06-03 at 12 15 27 PM

Thank you all 😄

### PR DESCRIPTION
**Pull request by juopmu**

### CODE REVIEW

File: app/helpers/admin/templates_helper.rb [hunk 1]
```diff
@@ -10,7 +10,7 @@ def example_data
       selection_mail: {
         applicant_name: "Ruby",
         event_date: @event.scheduled_at.strftime("%d.%m.%Y"),
-        confirmation_deadline: (@event.confirmation_date + 5.days).strftime("%d.%m.%Y"),
+        confirmation_deadline: (@event.confirmation_date + @event.confirmation_deadline).strftime("%d.%m.%Y"),
```
Comment (simaofreitas) [inline app/helpers/admin/templates_helper.rb]: Seems we are repeating the same `strftime("%d.%m.%Y")` part of the code in multiple places. 
Maybe we could avoid the repetition and try ensure that the dates are always with the same format? Moving this to a helper could be an option.

Comment (simaofreitas) [reply app/helpers/admin/templates_helper.rb]: To be done in a separate PR :)
